Repository Black-EveryDay/black-everyday-server, pull requests merged in 2025-01, with the labels that each got.

#6 [#2] feat: 상품 생성 기능
  product-service/build.gradle
  product-service/src/main/java/com/ed/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/ed/productservice/application/port/out/BrandOutPort.java
  product-service/src/main/java/com/ed/productservice/application/port/out/ProductDetailPort.java
  product-service/src/main/java/com/ed/productservice/application/port/out/ProductOutPort.java
  product-service/src/main/java/com/ed/productservice/application/service/ProductCommandService.java
  product-service/src/main/java/com/ed/productservice/domain/BottomProduct.java
  product-service/src/main/java/com/ed/productservice/domain/ProductForCreate.java
  product-service/src/main/java/com/ed/productservice/domain/TopProduct.java
  product-service/src/main/java/com/ed/productservice/domain/vo/Brand.java
  product-service/src/main/java/com/ed/productservice/domain/vo/BrandType.java
  product-service/src/main/java/com/ed/productservice/domain/vo/Product.java
  product-service/src/main/java/com/ed/productservice/domain/vo/ProductCategory.java
  product-service/src/main/java/com/ed/productservice/domain/vo/ProductStatus.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/BrandAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/ProductAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/ProductDetailAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/mapper/BottomSizeMapper.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/mapper/BrandMapper.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/mapper/ProductMapper.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/mapper/TopSizeMapper.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/BaseEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/BrandEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/ProductEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/size/BottomSizeEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/size/TopSizeEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/BottomSizeRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/BrandRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/ProductRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/TopSizeRepository.java
  product-service/src/main/java/com/ed/productservice/libs/common/ApiResponse.java
  product-service/src/main/java/com/ed/productservice/libs/common/ApiResponseUtils.java
  product-service/src/main/java/com/ed/productservice/libs/common/BrandNotFoundException.java
  product-service/src/main/java/com/ed/productservice/libs/common/CommonHttpMessageConverter.java
  product-service/src/main/java/com/ed/productservice/libs/common/ErrorCode.java
  product-service/src/main/java/com/ed/productservice/libs/common/ErrorResponse.java
  product-service/src/main/java/com/ed/productservice/libs/common/GlobalException.java
  product-service/src/main/java/com/ed/productservice/libs/common/ResponseWrapper.java
  product-service/src/main/java/com/ed/productservice/libs/config/JpaAuditingConfiguration.java
  product-service/src/main/java/com/ed/productservice/presentation/port/in/ProductCreateUseCase.java
  product-service/src/main/java/com/ed/productservice/presentation/web/ProductCommandController.java
  product-service/src/main/java/com/ed/productservice/presentation/web/request/BottomProductCreateRequest.java
  product-service/src/main/java/com/ed/productservice/presentation/web/request/ProductCommonInfo.java
  product-service/src/main/java/com/ed/productservice/presentation/web/request/TopProductCreateRequest.java
  product-service/src/main/java/com/ed/productservice/presentation/web/response/ProductCreateResponse.java
  product-service/src/main/resources/application.properties
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/ed/productservice/ProductCommandServiceApplicationTests.java
  product-service/src/test/java/com/ed/productservice/application/service/ProductCreateUseCaseTest.java
  product-service/src/test/java/com/ed/productservice/presentation/web/ProductCommandControllerSpringBootTest.java
  product-service/src/test/java/com/ed/productservice/presentation/web/ProductCommandControllerWebMvcTest.java
  product-service/src/test/resources/application-test.yml
Labels: enhancement

#7 [#3] feat: 회원가입 기능
  auth-service/build.gradle
  auth-service/src/main/java/com/ed/authservice/auth/adapter/in/web/AuthController.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/in/web/dto/SignUpRequest.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/BaseEntity.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/UserJpaEntity.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/UserJpaRepository.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/UserRepository.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/in/AuthSignUpCommand.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/in/AuthUseCase.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/out/AuthSignUpResponse.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/out/UserPersistencePort.java
  auth-service/src/main/java/com/ed/authservice/auth/application/service/AuthService.java
  auth-service/src/main/java/com/ed/authservice/auth/domain/User.java
  auth-service/src/main/java/com/ed/authservice/auth/domain/UserRole.java
  auth-service/src/main/java/com/ed/authservice/libs/common/ApiResponse.java
  auth-service/src/main/java/com/ed/authservice/libs/common/ApiResponseUtils.java
  auth-service/src/main/java/com/ed/authservice/libs/common/CommonHttpMessageConverter.java
  auth-service/src/main/java/com/ed/authservice/libs/common/ResponseWrapper.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/AdapterException.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/BlackEveryDayException.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/ErrorResponse.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/ExceptionStatus.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/GlobalExceptionHandler.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/ServiceException.java
  auth-service/src/main/resources/http/auth.http
  auth-service/src/test/java/com/ed/authservice/auth/adapter/in/web/AuthControllerTest.java
  auth-service/src/test/java/com/ed/authservice/auth/application/service/AuthServiceTest.java
  order-service/.gitattributes
  order-service/.gitignore
  order-service/build.gradle
  order-service/gradle/wrapper/gradle-wrapper.jar
  order-service/gradle/wrapper/gradle-wrapper.properties
  order-service/gradlew
  order-service/gradlew.bat
  order-service/settings.gradle
  order-service/src/main/java/com/ed/orderservice/OrderServiceApplication.java
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/application.yml
  order-service/src/test/java/com/ed/orderservice/OrderServiceApplicationTests.java
  payment-service/.gitattributes
  payment-service/.gitignore
  payment-service/build.gradle
  payment-service/gradle/wrapper/gradle-wrapper.jar
  payment-service/gradle/wrapper/gradle-wrapper.properties
  payment-service/gradlew
  payment-service/gradlew.bat
  payment-service/settings.gradle
  payment-service/src/main/java/com/ed/payment/PaymentServiceApplication.java
  payment-service/src/main/resources/application-local.yml
  payment-service/src/main/resources/application.yml
  payment-service/src/test/java/com/ed/payment/PaymentServiceApplicationTests.java
Labels: enhancement

#10 [#8] feat: 로그인 기능
  auth-service/build.gradle
  auth-service/src/main/java/com/ed/authservice/AuthServiceApplication.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/in/web/AuthController.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/in/web/dto/SignInRequest.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/BaseEntity.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/BaseJpaEntity.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/UserJpaEntity.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/UserJpaRepository.java
  auth-service/src/main/java/com/ed/authservice/auth/adapter/out/persistence/UserRepository.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/in/AuthSignInCommand.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/in/AuthUseCase.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/out/AuthSignInResponse.java
  auth-service/src/main/java/com/ed/authservice/auth/application/port/out/UserPersistencePort.java
  auth-service/src/main/java/com/ed/authservice/auth/application/service/AuthService.java
  auth-service/src/main/java/com/ed/authservice/libs/common/AuditorAwareImpl.java
  auth-service/src/main/java/com/ed/authservice/libs/config/AuthConfig.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/ExceptionStatus.java
  auth-service/src/main/java/com/ed/authservice/libs/exception/GlobalExceptionHandler.java
  auth-service/src/main/java/com/ed/authservice/libs/jwt/JwtProperties.java
  auth-service/src/main/java/com/ed/authservice/libs/jwt/JwtUtil.java
  auth-service/src/main/resources/application-jwt.yml
  auth-service/src/main/resources/application.yml
  auth-service/src/main/resources/http/auth.http
  auth-service/src/test/java/com/ed/authservice/auth/adapter/in/web/AuthControllerTest.java
  auth-service/src/test/java/com/ed/authservice/auth/application/service/AuthServiceTest.java
Labels: enhancement

#12 [#11] feat: 게이트 웨이, 유레카 세팅 및 인증 필터 개발
  auth-service/build.gradle
  auth-service/src/main/resources/application-local.yml
  auth-service/src/main/resources/http/auth.http
  eureka-server/.gitattributes
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/settings.gradle
  eureka-server/src/main/java/com/ed/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application-local.yml
  eureka-server/src/main/resources/application.yml
  eureka-server/src/test/java/com/ed/eurekaserver/EurekaServerApplicationTests.java
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/ed/gateway/GatewayApplication.java
  gateway/src/main/java/com/ed/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/java/com/ed/gateway/jwt/JwtProperties.java
  gateway/src/main/java/com/ed/gateway/jwt/JwtUtil.java
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/ed/gateway/GatewayApplicationTests.java
Labels: enhancement

#23 [#13] feat: 쿠폰 생성 기능
  event-service/.gitattributes
  event-service/.gitignore
  event-service/build.gradle
  event-service/gradle/wrapper/gradle-wrapper.jar
  event-service/gradle/wrapper/gradle-wrapper.properties
  event-service/gradlew
  event-service/gradlew.bat
  event-service/settings.gradle
  event-service/src/main/java/com/ed/eventservice/EventServiceApplication.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/web/CouponTemplateController.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/web/dto/CreateCouponRequest.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/web/dto/CreateCouponTemplateRequest.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/BaseJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponDiscountInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponExpirationInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponIssueInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponTemplateJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponUsageTargetInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/repository/CouponJpaRepository.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/repository/CouponTemplateJpaRepository.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/repository/CouponTemplateRepository.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/in/CouponUseCase.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/in/CreateCouponCommand.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/in/CreateCouponTemplateCommand.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/out/CouponTemplatePersistencePort.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/out/dto/CreateCouponTemplateResponse.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/service/CouponService.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/Coupon.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/CouponTemplate.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/enums/CouponIssuanceType.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/enums/CouponIssuerType.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/enums/CouponUsageTargetType.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/enums/DiscountType.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/mapper/CouponMapper.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/mapper/CouponTemplateMapper.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/vo/CouponDiscountInfo.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/vo/CouponExpirationInfo.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/vo/CouponIssueInfo.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/vo/CouponUsageTargetInfo.java
  event-service/src/main/java/com/ed/eventservice/libs/common/ApiResponse.java
  event-service/src/main/java/com/ed/eventservice/libs/common/ApiResponseUtils.java
  event-service/src/main/java/com/ed/eventservice/libs/common/AuditorAwareImpl.java
  event-service/src/main/java/com/ed/eventservice/libs/common/CommonHttpMessageConverter.java
  event-service/src/main/java/com/ed/eventservice/libs/common/ResponseWrapper.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/AdapterException.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/BlackEveryDayException.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/ErrorResponse.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/ExceptionStatus.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/GlobalExceptionHandler.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/ServiceException.java
  event-service/src/main/resources/application-local.yml
  event-service/src/main/resources/application.yml
  event-service/src/main/resources/http/event.http
  event-service/src/test/java/com/ed/eventservice/EventServiceApplicationTests.java
  event-service/src/test/java/com/ed/eventservice/coupon/adapter/in/web/CouponTemplateControllerTest.java
  gateway/src/main/resources/application-local.yml
Labels: enhancement

#35 [#5] feat: 결제 요청 검증
  payment-service/src/main/avro/order_payment_confirm_request_v1.avsc
  payment-service/src/main/java/com/ed/payment/application/port/in/ConfirmPaymentCommand.java
  payment-service/src/main/java/com/ed/payment/application/service/ConfirmPaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/HandleFailPaymentService.java
  payment-service/src/main/java/com/ed/payment/domain/Payment.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/mq/OrderPaymentConfirmConsumer.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/entity/PaymentJpaEntity.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/SpringDataPaymentRepository.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossConfirmPayment.java
  payment-service/src/main/java/com/ed/payment/libs/common/constant/CustomHttpHeaders.java
  payment-service/src/main/java/com/ed/payment/libs/common/exception/ErrorCode.java
  payment-service/src/test/java/com/ed/payment/application/service/ConfirmPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/HandleFailPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossConfirmPaymentTest.java
  payment-service/src/test/java/com/ed/payment/presentation/in/web/ConfirmPaymentControllerTest.java
Labels: enhancement

#36 [#34] feat: 내 결제 대기 목록 조회
  payment-service/src/main/java/com/ed/payment/application/port/in/GetMyReadyPaymentsUseCase.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/PaymentResponse.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/ReadPaymentPort.java
  payment-service/src/main/java/com/ed/payment/application/service/GetMyReadyPaymentsService.java
  payment-service/src/main/java/com/ed/payment/application/service/HandlerFailPaymentService.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/mq/OrderPaymentConsumer.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/SpringDataPaymentRepository.java
  payment-service/src/main/java/com/ed/payment/presentation/in/web/GetMyReadyPaymentController.java
  payment-service/src/main/resources/http/payment.http
  payment-service/src/test/java/com/ed/payment/application/service/GetMyReadyPaymentsServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/HandlerFailPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/presentation/in/web/GetMyReadyPaymentControllerTest.java
Labels: enhancement

#37 [#31] feat: 상품 서비스 (스키마, 환경설정 변경)
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application-prod.yml
  product-service/src/main/resources/db/V1_create.sql
Labels: enhancement

#40 [#39] feat: 결제 생성
  payment-service/build.gradle
  payment-service/src/main/avro/OrderPaymentResponse.avsc
  payment-service/src/main/avro/order_payment_create_request_v1.avsc
  payment-service/src/main/java/com/ed/payment/application/port/in/CreatePaymentUseCase.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/PaymentResponse.java
  payment-service/src/main/java/com/ed/payment/application/service/ConfirmPaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/CreatePaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/HandleFailPaymentService.java
  payment-service/src/main/java/com/ed/payment/infrastructure/in/mq/OrderPaymentCreate.java
  payment-service/src/main/java/com/ed/payment/infrastructure/in/mq/config/KafkaConsumerConfig.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/mq/OrderPaymentConfirmConsumer.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/mq/OrderPaymentProducer.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/PaymentPgMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossConfirmPayment.java
  payment-service/src/main/java/com/ed/payment/libs/common/constant/KafkaTopics.java
  payment-service/src/test/java/com/ed/payment/application/service/ConfirmPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/CreatePaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/GetMyReadyPaymentsServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/HandleFailPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/presentation/in/web/GetMyReadyPaymentControllerTest.java
Labels: enhancement

#41 [#38] 쿠폰 사용 ORDER ID 양식 변경
  event-service/build.gradle
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/internal/CouponInternalController.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/internal/dto/UseCouponRequest.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponStatusChangeLogJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/in/CouponUseCommand.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/service/CouponService.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/service/CouponTemplateService.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/Coupon.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/vo/CouponStatusChangeLog.java
  event-service/src/main/resources/application-local.yml
  event-service/src/main/resources/http/event.http
  event-service/src/main/resources/schema.sql
  event-service/src/test/java/com/ed/eventservice/coupon/adapter/in/internal/CouponInternalControllerTest.java
Labels: bug

#48 [#44] feat: 쿠폰 수동 발급 기능 개발
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/web/CouponController.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/in/web/dto/IssueCouponRequest.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/BaseJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponDiscountInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponExpirationInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponIssueInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponStatusChangeLogJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponTemplateJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/adapter/out/persistence/entity/CouponUsageTargetInfoJpaEntity.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/in/CouponUseCase.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/in/IssueCouponCommand.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/port/out/dto/IssueCouponResponse.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/service/CouponService.java
  event-service/src/main/java/com/ed/eventservice/coupon/application/service/CouponTemplateService.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/Coupon.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/CouponTemplate.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/enums/CouponUsageTargetType.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/mapper/CouponMapper.java
  event-service/src/main/java/com/ed/eventservice/coupon/domain/mapper/CouponTemplateMapper.java
  event-service/src/main/java/com/ed/eventservice/libs/exception/ExceptionStatus.java
  event-service/src/main/resources/http/event.http
  event-service/src/main/resources/schema.sql
  event-service/src/test/java/com/ed/eventservice/coupon/adapter/in/web/CouponControllerTest.java
Labels: enhancement

#51 [#46] feat: 상품 가격에 대한 버전 추가
  product-service/build.gradle
  product-service/src/main/java/com/ed/productservice/application/port/out/ProductOutPort.java
  product-service/src/main/java/com/ed/productservice/application/service/ProductCommandService.java
  product-service/src/main/java/com/ed/productservice/domain/vo/Product.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/ProductAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/ProductQueryAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/internal/StockAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/mapper/ProductMapper.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/BaseEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/ProductEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/entity/ProductPriceVersionEntity.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/ProductPriceVersionRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/ProductQueryDslRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/ProductRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/scheduler/DistributedStockRollback.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/scheduler/StockRollbackScheduler.java
  product-service/src/main/java/com/ed/productservice/libs/common/ErrorCode.java
  product-service/src/main/java/com/ed/productservice/presentation/web/ProductQueryController.java
Labels: enhancement

#53 [#24] feat: 상품 목록 검색 기능 개선
  product-service/build.gradle
  product-service/docker-compose.yml
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/ProductElasticQueryAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/elasticsearch/SearchProduct.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/elasticsearch/AdvancedSearchProductRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/elasticsearch/SearchProductRepository.java
  product-service/src/main/java/com/ed/productservice/libs/config/ElasticConfig.java
  product-service/src/main/java/com/ed/productservice/presentation/web/ProductElasticsearchController.java
  product-service/src/main/java/com/ed/productservice/presentation/web/response/ProductDetailResponse.java
  product-service/src/main/resources/application-dev.yml
Labels: enhancement

#56 [#47] refactor: 결제 서비스 리팩토링
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/CreatePaymentHistoryPort.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/UpdatePaymentPort.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/dtos/CreateCancelPaymentHistoryRequest.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/dtos/CreateConfirmPaymentHistoryRequest.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/dtos/UpdateCancelPaymentRequest.java
  payment-service/src/main/java/com/ed/payment/application/port/out/pg/dtos/PaymentCanceledResponse.java
  payment-service/src/main/java/com/ed/payment/application/port/out/pg/dtos/PaymentDoneResponse.java
  payment-service/src/main/java/com/ed/payment/application/service/CancelPaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/ConfirmPaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/CreatePaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/HandleFailPaymentService.java
  payment-service/src/main/java/com/ed/payment/application/service/OutPortPersistenceMapper.java
  payment-service/src/main/java/com/ed/payment/domain/PaymentStatus.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/entity/PaymentHistoryJpaEntity.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/entity/PaymentJpaEntity.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentHistoryPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentHistoryPersistenceMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/SpringDataPaymentHistoryRepository.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/PaymentPgMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossCancelPayment.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossConfirmPayment.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/dtos/TossPaymentCanceledResponse.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/pg/toss/dtos/TossPaymentDoneResponse.java
  payment-service/src/main/java/com/ed/payment/libs/common/constant/HttpHeaders.java
  payment-service/src/main/java/com/ed/payment/libs/common/entity/BaseTimeByJpaEntity.java
  payment-service/src/main/resources/schema.sql
  payment-service/src/test/java/com/ed/payment/application/service/CancelPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/ConfirmPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/CreatePaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/application/service/HandleFailPaymentServiceTest.java
  payment-service/src/test/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossCancelPaymentTest.java
  payment-service/src/test/java/com/ed/payment/infrastructure/out/pg/toss/RestTemplateTossConfirmPaymentTest.java
  payment-service/src/test/java/com/ed/payment/presentation/in/web/ConfirmPaymentControllerTest.java
Labels: refactor

#58 [#45] feat: 주문 결제 요청
  order-service/build.gradle
  order-service/src/main/java/com/ed/orderservice/application/port/in/CouponUseInPort.java
  order-service/src/main/java/com/ed/orderservice/application/port/in/ProductStockInPort.java
  order-service/src/main/java/com/ed/orderservice/application/port/out/OrderEventCreatedOutPort.java
  order-service/src/main/java/com/ed/orderservice/application/port/out/OrderEventStatusUpdateOutPort.java
  order-service/src/main/java/com/ed/orderservice/application/port/out/OrderPaymentCreateOutPort.java
  order-service/src/main/java/com/ed/orderservice/application/port/out/OrderStatusUpdateOutPort.java
  order-service/src/main/java/com/ed/orderservice/application/service/CreateOrderService.java
  order-service/src/main/java/com/ed/orderservice/application/service/OrderPaymentCreateService.java
  order-service/src/main/java/com/ed/orderservice/application/service/ProductStockService.java
  order-service/src/main/java/com/ed/orderservice/application/service/serializer/OrderPaymentRequestSerializer.java
  order-service/src/main/java/com/ed/orderservice/domain/enums/OrderDeliveryStatus.java
  order-service/src/main/java/com/ed/orderservice/domain/enums/OrderEventStatus.java
  order-service/src/main/java/com/ed/orderservice/domain/enums/OrderStatus.java
  order-service/src/main/java/com/ed/orderservice/domain/mapper/OrderEventMapper.java
  order-service/src/main/java/com/ed/orderservice/domain/mapper/OrderMapper.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/Order.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/OrderBase.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/OrderCreatedEvent.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/OrderEvent.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/OrderEventJpaRepository.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/OrderJpaRepository.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/adapter/OrderEventCreatedAdapter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/adapter/OrderEventStatusUpdateAdapter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/adapter/OrderStatusUpdateAdapter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/converter/OrderStatusConverter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderDeliveryEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderEventEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderEventStatusHistoryEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderItemCouponEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderItemEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/OrderStatusHistoryEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/common/BaseTimeByJpaEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/common/BaseTimeJpaEntity.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/entity/common/JpaAuditingConfig.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/config/FeignClientConfig.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/event/CouponClient.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/event/adapter/CouponUseAdapter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/event/config/EventFeignErrorDecoder.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/product/ProductClient.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/product/adapter/ProductStockAdapter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/product/config/ProductFeignErrorDecoder.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/product/dto/ProductBrandInfo.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/product/dto/ProductReservationResponse.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/external/fegin/domain/product/dto/StockDecreaseResponse.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/message/kafka/adapter/OrderPaymentCreateAdapter.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/message/kafka/config/KafkaProducerConfig.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/message/kafka/payment/OrderPaymentCreateProducer.java
  order-service/src/main/java/com/ed/orderservice/libs/common/AsyncConfiguration.java
  order-service/src/main/java/com/ed/orderservice/libs/response/ApiResponse.java
  order-service/src/main/java/com/ed/orderservice/presentaion/port/in/CreateOrderUseCase.java
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/db/schema.sql
  order-service/src/main/resources/http/evenet.http
  order-service/src/main/resources/http/order.http
  order-service/src/main/resources/http/product.http
Labels: enhancement

#60 [#59] feat: 주문 정산 조회
  order-service/src/main/java/com/ed/orderservice/application/port/in/command/OrderSettlementCommand.java
  order-service/src/main/java/com/ed/orderservice/application/port/out/OrderGetOutPort.java
  order-service/src/main/java/com/ed/orderservice/application/service/OrderItemCouponService.java
  order-service/src/main/java/com/ed/orderservice/application/service/OrderSettlementService.java
  order-service/src/main/java/com/ed/orderservice/domain/mapper/OrderSettlementMapper.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/settlement/CouponSettlement.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/settlement/OrderItemSettlement.java
  order-service/src/main/java/com/ed/orderservice/domain/vo/order/settlement/OrderSettlement.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/adapter/OrderGetAdapter.java
  order-service/src/main/java/com/ed/orderservice/presentaion/port/in/OrderSettlementUseCase.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/controller/OrderController.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/controller/internal/OrderSettlementInternalController.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/response/domain/orderCreate/NewPurchaseOrderMessageResponse.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/response/domain/orderCreate/OrderDeliveryInfo.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/response/domain/orderSettlement/CouponDetail.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/response/domain/orderSettlement/OrderItemDetail.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/response/domain/orderSettlement/OrderSettlementResponse.java
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/db/init.sql
  order-service/src/main/resources/http/order.http
  order-service/src/test/java/com/ed/orderservice/presentaion/web/controller/OrderControllerTest.java
  order-service/src/test/java/com/ed/orderservice/presentaion/web/controller/internal/OrderSettlementInternalControllerTest.java
Labels: enhancement

#65 [#57] feat: 인기 상품 캐싱
  product-service/build.gradle
  product-service/src/main/java/com/ed/productservice/domain/vo/ProductDetails.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/ProductQueryAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/adapter/elasticsearch/ProductElasticQueryAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/elasticsearch/LogDetails.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/ProductQueryDslRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/ProductRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/repository/elasticsearch/LogDetailsRepository.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/scheduler/DistributedLockScheduler.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/scheduler/PopularProductCacheAdapter.java
  product-service/src/main/java/com/ed/productservice/infrastructure/persistence/scheduler/SchedulerUtil.java
  product-service/src/main/java/com/ed/productservice/libs/config/RedisCacheConfig.java
  product-service/src/main/java/com/ed/productservice/presentation/web/ProductElasticsearchController.java
  product-service/src/main/java/com/ed/productservice/presentation/web/ProductQueryController.java
  product-service/src/main/java/com/ed/productservice/presentation/web/response/ProductDetailResponse.java
  product-service/src/main/resources/logback-spring.xml
Labels: enhancement

#69 [#68] 주문 정산 다건 조회 리팩토링
  order-service/src/main/java/com/ed/orderservice/application/port/in/command/OrderSettlementCommand.java
  order-service/src/main/java/com/ed/orderservice/application/port/out/OrderGetOutPort.java
  order-service/src/main/java/com/ed/orderservice/application/service/OrderSettlementService.java
  order-service/src/main/java/com/ed/orderservice/domain/mapper/OrderSettlementMapper.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/OrderJpaRepository.java
  order-service/src/main/java/com/ed/orderservice/infrastructure/db/mysql/adapter/OrderGetAdapter.java
  order-service/src/main/java/com/ed/orderservice/presentaion/port/in/OrderSettlementUseCase.java
  order-service/src/main/java/com/ed/orderservice/presentaion/web/controller/internal/OrderSettlementInternalController.java
  order-service/src/test/java/com/ed/orderservice/presentaion/web/controller/internal/OrderSettlementInternalControllerTest.java
Labels: refactor

#71 [Feature/Settlement-Service] 일일 정산
  payment-service/build.gradle
  payment-service/gradle.properties
  payment-service/src/main/java/com/ed/payment/PaymentServiceApplication.java
  payment-service/src/main/java/com/ed/payment/application/port/out/feign/GetOrderSettlementsPort.java
  payment-service/src/main/java/com/ed/payment/application/port/out/feign/dtos/OrderSettlementResponse.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/CreateDailySettlementPort.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/GetPaymentPort.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/UpdatePaymentPort.java
  payment-service/src/main/java/com/ed/payment/application/port/out/persistence/dtos/SettleablePaymentResponse.java
  payment-service/src/main/java/com/ed/payment/domain/DailySettlement.java
  payment-service/src/main/java/com/ed/payment/domain/PaymentStatus.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/batch/chunk/reader/SettleablePaymentCustomItemReader.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/batch/chunk/reader/SettleablePaymentReaderConfig.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/batch/chunk/writer/DailySettlementItemWriter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/batch/job/DailySettlementJobConfig.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/batch/listener/JobDurationListener.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/feign/config/FeignClientConfig.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/feign/config/FeignErrorDecoder.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/feign/domain/order/OrderClient.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/feign/domain/order/OrderFeignAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/config/QueryDslConfig.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/entity/DailySettlementJpaEntity.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/entity/MonthlySettlementJpaEntity.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/entity/PaymentJpaEntity.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/DailySettlementPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentPersistenceMapper.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/PaymentQueryDslAdapter.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/persistence/repository/SpringDataPaymentRepository.java
  payment-service/src/main/java/com/ed/payment/infrastructure/out/scheduler/DailySettlementBatchScheduler.java
  payment-service/src/main/java/com/ed/payment/libs/common/response/ApiResponse.java
  payment-service/src/main/java/com/ed/payment/presentation/in/web/RequestPaymentViewController.java
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/schema.sql
Labels: enhancement

#75 [#67] feat: 테스트 코드수정
  product-service/src/main/java/com/ed/productservice/domain/vo/Product.java
  product-service/src/test/java/com/ed/productservice/ProductCommandServiceApplicationTests.java
  product-service/src/test/java/com/ed/productservice/application/service/ProductUseCaseTest.java
  product-service/src/test/java/com/ed/productservice/presentation/web/ProductCommandControllerSpringBootTest.java
  product-service/src/test/java/com/ed/productservice/presentation/web/internal/ProductInternalControllerTest.java
  product-service/src/test/resources/application-test.yml
Labels: bug
